### ISSUE TITLE
ttf字体中对应的Unicode编码和实际的图标是否有某种规律的映射？

### ISSUE THREAD

**Issue by HalfSweet** [qwd/Icons#14]
在使用ttf字体作为图标的时候，我发现ttf字体中每个图标与获取到icon码似乎并不是一一对应，请问下是否有存在某种规律的映射？还是并无规律，只能自行查找

**Comment by guox** [comment]
hi, 请告知哪个字体与icon代码不一致？理论上应该是相互对应的。

**Comment by HalfSweet** [comment]
比如说“晴天”的图标，在icon码里面是100，但是对应的Unicode码却是0xF101;
![图片](https://user-images.githubusercontent.com/60973476/169255533-078458a2-f4d3-4188-a392-f608f1fd250c.png)

“大雪”图标，在icon码里面是402，在对应的Unicode码里面却是0xF122
![图片](https://user-images.githubusercontent.com/60973476/169255657-8ec5e175-fd1e-4227-9a1d-9bfc16217237.png)
以上示例不胜枚举，因此我想知道是否有一定的规律能够将icon码与实际字符的Unicode码结合起来呢

**Comment by QWRDA** [comment]
你好，请通过CSS种定义的图标代码与API中的`iconCode`字段对应，例如
```html
<i class="qi-152"></i>
```
