### ISSUE TITLE
图标上色

### ISSUE THREAD

**Issue by Shalomw** [qwd/Icons#19]
根据上色需求的不同把图标多分几个path。比如雷阵雨图标，图标中的云、闪电和雨点都在一个path里，不方便上色

**Comment by Alan-CRL** [comment]
Yes, I suggest so

**Comment by QWRDA** [comment]
这恐怕是一个大工程，意味着需要将所有图标重新画一遍，我们目前暂时没有此类计划，不过可以考虑在新增加的图标提供更多path。

**Comment by guox** [comment]
元旦之后我们开始陆续调整图标的path

**Comment by guox** [comment]
所有图标设计文件已经[发布在figma](https://www.figma.com/community/file/1196353857920331062)，你可以创建新的图标并使用[本项目编译新的字体](https://icons.qweather.com/customize)。
