### ISSUE TITLE
库中没有发现和图标名称相关的文件

### ISSUE THREAD

**Issue by Cierra-Runis** [qwd/Icons#40]
https://dev.qweather.com/docs/resource/warning-info/#warning-type

https://dev.qweather.com/docs/resource/icons/#%E6%9C%88%E7%9B%B8%E5%9B%BE%E6%A0%87

https://dev.qweather.com/docs/resource/icons/#%E5%A4%A9%E6%B0%94%E5%9B%BE%E6%A0%87

这三处的中文名称分的很散，而且看上去也不是最新的，有无和 https://github.com/qwd/Icons/tree/main/font/qweather-icons.json 相对应的中文名称呢，实际上如果有多语言支持的话也应该写别的语言的。

例如：

```json
{
  "100": {
    "code_point": 61697,
    "zh_cn": "晴",
    "en_us": "sunny"
  },
}
```

最好也能更新一下网页。

**Comment by QWRDA** [comment]
Hi 文档中的内容应该是最新的，但其实你并需要这些文档，只需要根据API中返回的`icon`去使用对应的图标即可。
关于多语言，图标本身并不存在多语言，如果需要数据中的多语言，请使用请求参数[lang](https://dev.qweather.com/docs/resource/language/)

**Comment by Cierra-Runis** [comment]
> Hi 文档中的内容应该是最新的，但其实你并需要这些文档，只需要根据API中返回的`icon`去使用对应的图标即可。 关于多语言，图标本身并不存在多语言，如果需要数据中的多语言，请使用请求参数[lang](https://dev.qweather.com/docs/resource/language/)

那我就用文档里的名称吧，谢谢解释了
