### ISSUE TITLE
如何在 Android 中使用图标

### ISSUE THREAD

**Issue by tbontb-iaq** [qwd/Icons#43]
根据这个 [Issue](https://github.com/qwd/Icons/issues/14)，Icon 码和 Unicode 没有对应规律，只能通过 css 使用。那么如何在非 Web 平台如 Android 使用图标呢？

**Comment by guox** [comment]
我们想一下如何处理，目前来看，可以通过[font/qweather-icons.json](https://github.com/qwd/Icons/blob/main/font/qweather-icons.json)这个文件做一些映射，其中的值进行16进制转换后即是unicode

**Comment by tbontb-iaq** [comment]
非常感谢，我的问题解决了。
我在想，是否能够更加简单的使用图标。比如 [Google Material Icon](https://developers.google.com/fonts/docs/material_symbols?hl=zh-cn#use_in_web) 使用文字内容而不是 Unicode 来定位符号：

```html
<p>这将显示一个搜索图标</p>
<span style="font-family: 'Material Symbols Outlined'" >search</span>
```

**Comment by guox** [comment]
现在也是可以的，参考 https://icons.qweather.com/usage/， 比如
`<span class="qi-100"></span>`
或
`<span class="qi-sunny"></span>`

**Comment by tbontb-iaq** [comment]
这不一样，这样实际上还是 Unicode，只不过对应关系在 css 文件里定义了。
现在的用法类似于：
```html
<span style="font-family: qweather-icons">&#61701;<span>
```

**Comment by guox** [comment]
@tbontb-iaq 不好意思这么久才有机会回复你。我参考了Google那个icon项目，他们应该是使用单词替代了字体里的16进制的值。在Web开发中，`<span class="qi-100"></span>`和`<span style="font-family: qweather-icons">100<span>`貌似不好说孰胜孰劣，感觉差不多。我不是android开发，所以我比较好奇的是，在什么情况下会用到16进制的值？

**Comment by tbontb-iaq** [comment]
在 Web 开发中确实没有区别，但是在非 Web 平台 Google Icon 的方式更加方便。
事实上这个 Issue 询问的是在 Android 中使用的问题，而这个问题已经解决了，只不过麻烦了一点。
如果没有其他问题的话这个 Issue 可以关闭了。
