### ISSUE TITLE
是否还会提供 icon 的 png 版本？ 

### ISSUE THREAD

**Issue by sxxhlx** [qwd/Icons#69]
我这里有一个主要是kindle使用的天气页面，https://clock.buttercatann.com/ ，kindle好像是不支持svg的。所以对图标的png版本有诉求，请问还会有支持计划吗？

**Comment by QWRDA** [comment]
绝大部分的图片软件都可以将svg转化为png，或在[figma](https://www.figma.com/community/file/1196353857920331062)中直接导出png格式
