### ISSUE TITLE
不兼容老图标包了？

### ISSUE THREAD

**Issue by chenxuuu** [qwd/Icons#9]
之前的png图标很多编号都没有了，新的打包文件也没有png格式
这么随意改来改去是不是不太好

**Comment by QWRDA** [comment]
1. 你仍然可以使用原来的图标，但我们不会再进行更新，原图标也提供了ai格式源文件，如果你愿意可以自行修改
2. 很明显，使用SVG格式可以方便的转化为任意格式或更加方便在你的开发项目中使用
3. 没有理解你所谓的“改来改去”的意思

**Comment by chenxuuu** [comment]
1. 原来的图标包不全，比如151号图标就没有
2. 前端项目≠大部分项目
3. 参考第1点，之前（至少一周前）从接口返回的编号，不会出现图标缺失的情况

**Comment by QWRDA** [comment]
你好，旧的图标项目已经不再更新，因此不会适配新的天气代码。 你可以自行下载源文件进行修改或添加，也可以使用新的图标项目，如果有好的设计或code，欢迎提交PR。
